import React from 'react';
import '../styles/imagePage.css'
import image2 from "../resources/phytoplankton/diatomaceas.webp" 
import image3 from "../resources/phytoplankton/singlediatomacea.jpg"
import ButtonGroup from '@mui/material/Button';
import Button from '@mui/material/Button';
//import { useNavigate } from 'react-router-dom';

function InfoPage() {

  //const navigate = useNavigate()
//
  //const navigateNext = () => {
  //  navigate("/phytoplanktons1")
  //}
//
  //const navigatePrevious = () => {
  //  navigate("/previous1")
  //}

  return (
    <div id="imagePage">
      <h1>Phytoplankton comes in a wide variety of shapes</h1>
      <h2>Subtítulo</h2>
      <p>BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      </p>
      
      <div className="image-row">
        <div className="image-and-subtitle">
          <img src={image2} className="image-div" alt="Image 1" />
          <p>Daniel hosomi</p>
        </div>
        <div  className="image-and-subtitle">
          <img src={image2} className="image-div" alt="Image 2" />
          <p>Daniel hosomi</p>
        </div>
        <div  className="image-and-subtitle">
          <img src={image3} className="image-div" alt="Image 3" />
          <p>Daniel Hosomi</p>
        </div>
        
      </div>

      <div className="paragraph-image-row">
        <p>BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      BRABES BRABES BRABESBRABESBRABES BRABES BRABESBRABESBRABESBRABESBRABES
      </p>
        <div className='side-image-div'>
        </div>
      </div>
      <ButtonGroup variant="contained">
        <Button>Previous</Button>
        <Button>Next</Button>
      </ButtonGroup>
      
    </div>
  );
}

export default InfoPage;
